In [2]:
import numpy as np

In [3]:
list_nilai = [20,40,60,80]
arr = np.array([1,2,3,4,5])
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [5]:
arr = np.array(list_nilai)
print(arr, type(arr))

[20 40 60 80] <class 'numpy.ndarray'>


In [9]:
arr = np.ones((5,3))
print(arr, type(arr))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] <class 'numpy.ndarray'>


In [16]:
arr = np.arange(5,50,5)
print(arr, type(arr) (arr.shape))

[ 5 10 15 20 25 30 35 40 45] [4.67296746e-307 1.69121096e-306 2.31420855e-306 1.89146896e-307
 7.56571288e-307 3.11525958e-307 1.24610723e-306 1.29061142e-306
 5.53353523e-322]


In [19]:
print(list_nilai)

[20, 40, 60, 80]


In [21]:
print(arr)

[ 5 10 15 20 25 30 35 40 45]


In [23]:
print(arr[3])

20


In [27]:
nilai = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [28]:
nilai

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
print(nilai[1:3])

[[ 5  6  7  8]
 [ 9 10 11 12]]


In [34]:
arr

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [36]:
print(arr[3])

20


In [37]:
print(nilai)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [39]:
arr = np.arange(20,50,5).reshape((2,3))
print(arr)

[[20 25 30]
 [35 40 45]]


In [44]:
arr2 = np.arange(20,50,5).reshape((2,3))
print(arr2)

[[20 25 30]
 [35 40 45]]


In [45]:
arr + arr2

array([[40, 50, 60],
       [70, 80, 90]])

In [46]:
arr = (np.random.random((3,5)) * 200).astype(int)
print(arr)

[[177 149 146  64  37]
 [138 160 108 155  10]
 [ 53 176 177  67  65]]


In [51]:
print(arr.sum())
print(arr.sum(axis=0))
print(arr.sum(axis=1))


1682
[368 485 431 286 112]
[573 571 538]


In [72]:
print(arr.mean())
print((arr.mean(axis=0))).astype(int)
print(arr.mean(axis=1))

112.13333333333334
[122.66666667 161.66666667 143.66666667  95.33333333  37.33333333]


AttributeError: 'NoneType' object has no attribute 'astype'

In [54]:
#berlaku untuk max min juga

In [55]:
print(arr)

[[177 149 146  64  37]
 [138 160 108 155  10]
 [ 53 176 177  67  65]]


In [57]:
divisible_by_2 = (arr % 2 == 0)
print(arr[divisible_by_2])

[146  64 138 160 108  10 176]


In [58]:
odd = (arr % 2 != 0)
print(arr[odd])

[177 149  37 155  53 177  67  65]


In [59]:
odd = (arr % 2 != 0)
big = (arr >100)
print (arr[odd & big])

[177 149 155 177]


In [6]:
arr_harga_jual = np.array([ [10000],
                            [15000],
                            [20000]])
print (arr_harga_jual)

[[10000]
 [15000]
 [20000]]


In [4]:
arr_penjualan = np.array(
    [   [2, 5, 6, 7, 4],
        [3, 4, 2, 1, 4],
        [2, 3, 4, 6, 2]])

arr_penjualan = arr_penjualan.T
print (arr_penjualan)

[[2 3 2]
 [5 4 3]
 [6 2 4]
 [7 1 6]
 [4 4 2]]


In [7]:
arr_penjualan.dot(arr_harga_jual)

array([[105000],
       [170000],
       [170000],
       [205000],
       [140000]])

In [22]:
arr_penjualan = arr_penjualan.T
print (arr_penjualan)

[[2 5 6 7 4]
 [3 4 2 1 4]
 [2 3 4 6 2]]


In [23]:
arr_harga_jual = arr_harga_jual.T
print (arr_harga_jual)

[[10000 15000 20000]]


In [24]:
arr_harga_jual.dot(arr_penjualan)

array([[105000, 170000, 170000, 205000, 140000]])